######################################################################
# Automatically generated by qmake (3.0) Tue Apr 14 19:01:35 2015
######################################################################

TEMPLATE = app
TARGET = WidgetsAppliction
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += mainwindow.h
#FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
