MenuEdit: MenuItem Class Reference
MenuItem Class Reference
The MenuItem class is main component, from which derive composites and leaves and also class for menu item - leave of our hierarchy.
#include <menuitem.h>
Public Member Functions
MenuItem (const std::string &pTitle, double pPrice=0.0, std::string pDescription=std::string())
virtual ~MenuItem ()
std::string description () const
double price () const
void accept (MenuVisitor *visitor)
Public Member Functions inherited from Composite
Composite (const std::string &pTitle)
~Composite ()
void addSubitem (Composite *pItem)
int subitemsCount () const
Composite * child (int pIndex) const
Composite * parent () const
std::string title () const
Detailed Description
The MenuItem class is main component, from which derive composites and leaves and also class for menu item - leave of our hierarchy.
Definition at line 14 of file menuitem.h.
Constructor & Destructor Documentation
MenuItem::MenuItem (const std::string & pTitle, double pPrice = 0.0, std::string pDescription = std::string()) inline
Definition at line 18 of file menuitem.h.
         : Composite(pTitle),
           mPrice(pPrice),
           mDescription(pDescription)
     {}
MenuItem::~MenuItem () virtual
Definition at line 7 of file menuitem.cpp.
 {
 }
Member Function Documentation
void MenuItem::accept (MenuVisitor * visitor)
Definition at line 22 of file menuitem.cpp.
References MenuVisitor::visit().
 {
     visitor->visit(this);
 }
std::string MenuItem::description () const
Definition at line 12 of file menuitem.cpp.
Referenced by ConsolePrintMenuVisitor::visit().
 {
     return mDescription;
 }
double MenuItem::price () const
Definition at line 17 of file menuitem.cpp.
Referenced by ConsolePrintMenuVisitor::visit().
 {
     return mPrice;
 }
The documentation for this class was generated from the following files:
menuitem.h
menuitem.cpp