MenuEdit: ConsolePrintMenuVisitor Class Reference
ConsolePrintMenuVisitor Class Reference
#include <consoleprintmenuvisitor.h>
Public Member Functions
void visit (MenuItem *item)
void visit (Menu *menu)
Detailed Description
Definition at line 8 of file consoleprintmenuvisitor.h.
Member Function Documentation
void ConsolePrintMenuVisitor::visit (MenuItem * item) virtual
Implements MenuVisitor.
Definition at line 23 of file consoleprintmenuvisitor.cpp.
References MenuItem::description(), MenuItem::price(), and Composite::title().
 {
     std::string lIndentString = indent(item);
     std::cout << lIndentString << "> " << item->title() << "    :        " << item->price() << "$" << std::endl;
     if (!item->description().empty())
     {
         std::cout << lIndentString << "    ::::" << item->description() << "::::" << std::endl;
     }
 }
void ConsolePrintMenuVisitor::visit (Menu * menu) virtual
Implements MenuVisitor.
Definition at line 35 of file consoleprintmenuvisitor.cpp.
References Composite::title().
 {
     std::cout << indent(menu) << "[" << menu->title() << "]" << std::endl;
 }
The documentation for this class was generated from the following files:
consoleprintmenuvisitor.h
consoleprintmenuvisitor.cpp